IPK_DEST = ../..
include ../../Mk/pkgdata.mk

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = usr/local/lib/mjpg-streamer/input_opencv.so

include ../../Mk/remote_build.mk
include ../../Mk/ipk.mk
