include ../Mk/ipkg.pre.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = usr/local/include/python3.4m \
		  usr/local/lib/pkgconfig/python*3* \
		  usr/local/lib/python3.4/config-3.4m/libpython3.4m.a

include ../Mk/ipkg.post.mk
