include ../Mk/ipkg.pre.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = --exclude=usr/local/include/python3.5m/pyconfig.h \
		  usr/local/include/python3.5m \
		  usr/local/lib/pkgconfig/python*3* \
		  usr/local/lib/python3.5/config-3.5m/libpython3.5m.a

include ../Mk/ipkg.post.mk
