include ../Mk/pkgdata.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = usr/local/bin/.debug/python3.5m \
		  usr/local/lib/.debug/libpython3* \
		  usr/local/lib/python3.5/lib-dynload/.debug

			include ../Mk/remote_build.mk
			include ../Mk/ipk.mk

include ../Mk/remote_build.mk
include ../Mk/ipk.mk