include ../Mk/ipkg.pre.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = usr/local/bin/.debug/python3.4m \
		  usr/local/lib/.debug/libpython3* \
		  usr/local/lib/python3.4/lib-dynload/.debug

include ../Mk/ipkg.post.mk
