include ../Mk/pkgdata.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = \
	usr/local/lib/libavcodec.a \
	usr/local/lib/libavdevice.a \
	usr/local/lib/libavfilter.a \
	usr/local/lib/libavformat.a \
	usr/local/lib/libavresample.a \
	usr/local/lib/libavutil.a \
	usr/local/lib/libswscale.a \
	usr/local/lib/pkgconfig/libavcodec.pc \
	usr/local/lib/pkgconfig/libavdevice.pc \
	usr/local/lib/pkgconfig/libavfilter.pc \
	usr/local/lib/pkgconfig/libavformat.pc \
	usr/local/lib/pkgconfig/libavresample.pc \
	usr/local/lib/pkgconfig/libavutil.pc \
	usr/local/lib/pkgconfig/libswscale.pc \
	usr/local/include/libavcodec \
	usr/local/include/libavdevice \
	usr/local/include/libavfilter \
	usr/local/include/libavformat \
	usr/local/include/libavresample \
	usr/local/include/libavutil \
	usr/local/include/libswscale

include ../Mk/remote_build.mk
include ../Mk/ipk.mk
