
BUILD_DEPS = python37-numpy opencv3-dev
RUNTIME_DEPS = python37-numpy, python37-opencv3 (>= 3.4)
PYDEPS = pybind11

PYPI_PACKAGE_NAME = robotpy-cscore
PYPI_PACKAGE_VERSION = 2019.0.2

include ../../Mk/remote_whl.mk
