
BUILD_DEPS = python36-numpy opencv3-dev
RUNTIME_DEPS = python36-numpy, python36-opencv3 (>= 3.2.0)
PYDEPS = pybind11

PYPI_PACKAGE_NAME = robotpy-cscore
PYPI_PACKAGE_VERSION = 2017.0.1

include ../../Mk/remote_whl.mk
