
BUILD_DEPS = openblas-dev gfortran gfortran-symlinks libgfortran-dev python38-numpy
RUNTIME_DEPS = openblas, libgfortran4, python38-numpy
PYDEPS = pybind11

PYPI_PACKAGE_NAME = scipy
PYPI_PACKAGE_VERSION = 1.4.1

include ../../Mk/remote_whl.mk
