
BUILD_DEPS = ATLAS-dev gfortran gfortran-symlinks python37-numpy
RUNTIME_DEPS = ATLAS (>= 3.10.3), libgfortran3, python37-numpy

PYPI_PACKAGE_NAME = scipy
PYPI_PACKAGE_VERSION = 1.2.0

include ../../Mk/remote_whl.mk
