
BUILD_DEPS = ATLAS-dev gfortran gfortran-symlinks python36-numpy
RUNTIME_DEPS = ATLAS (>= 3.10.3), libgfortran3, python36-numpy

PYPI_PACKAGE_NAME = scipy
PYPI_PACKAGE_VERSION = 1.0.0

include ../../Mk/remote_whl.mk
