IPK_DEST = ../..
include ../../Mk/pkgdata.mk

NO_FETCH_SOURCE = 1

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = usr/local/lib/mjpg-streamer/cvfilter_py.so

include ../../Mk/remote_build.mk
include ../../Mk/ipk.mk
