#ifndef ATL_INSTINFO_H
   #define ATL_INSTINFO_H

#define ATL_ARCH "ARMv732NEON"
#define ATL_INSTFLAGS "-1 0 -a 1 -l 1"
#define ATL_F2CDEFS "-DAdd_ -DF77_INTEGER=int -DStringSunStyle"
#define ATL_ARCHDEFS "-DATL_OS_Linux -DATL_ARCH_ARMv7 -DATL_CPUMHZ=667 -DATL_NEON -DATL_GAS_ARM"
#define ATL_DKCFLAGS "-O1 -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -fno-schedule-insns2 -fPIC"
#define ATL_DKC "/usr/bin/arm-nilrt-linux-gnueabi-gcc"
#define ATL_SKCFLAGS "-O1 -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -fno-expensive-optimizations -fPIC"
#define ATL_SKC "/usr/bin/arm-nilrt-linux-gnueabi-gcc"
#define ATL_DMCFLAGS "-O1 -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -fno-schedule-insns2 -fPIC"
#define ATL_DMC "/usr/bin/arm-nilrt-linux-gnueabi-gcc"
#define ATL_SMCFLAGS "-O1 -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -fno-expensive-optimizations -fPIC"
#define ATL_SMC "/usr/bin/arm-nilrt-linux-gnueabi-gcc"
#define ATL_ICCFLAGS "-DL2SIZE=4194304 -I/home/admin/ATLAS/BUILD/include -I/home/admin/ATLAS/BUILD/..//include -I/home/admin/ATLAS/BUILD/..//include/contrib -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DATL_OS_Linux -DATL_ARCH_ARMv7 -DATL_CPUMHZ=667 -DATL_NEON -DATL_GAS_ARM -DATL_DYLIBS -DATL_FULL_LAPACK -DATL_NCPU=2 -O1 -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -fno-expensive-optimizations -fPIC"
#define ATL_ICC "/usr/bin/arm-nilrt-linux-gnueabi-gcc"
#define ATL_F77FLAGS "-mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=softfp -O -fPIC"
#define ATL_F77 "/usr/bin/arm-nilrt-linux-gnueabi-gfortran"
#define ATL_DKCVERS "arm-nilrt-linux-gnueabi-gcc (GCC) 4.8.2"
#define ATL_SKCVERS "arm-nilrt-linux-gnueabi-gcc (GCC) 4.8.2"
#define ATL_DMCVERS "arm-nilrt-linux-gnueabi-gcc (GCC) 4.8.2"
#define ATL_SMCVERS "arm-nilrt-linux-gnueabi-gcc (GCC) 4.8.2"
#define ATL_ICCVERS "arm-nilrt-linux-gnueabi-gcc (GCC) 4.8.2"
#define ATL_F77VERS "GNU Fortran (GCC) 4.8.2"
#define ATL_SYSINFO "Linux roboRIO-2423-FRC 3.14.40-rt37-ni-3.2.0d0 #1 SMP PREEMPT RT Mon Oct 26 13:32:00 CDT 2015 armv7l GNU/Linux"
#define ATL_DATE    "Sat Dec 26 02:41:19 UTC 2015"
#define ATL_UNAM    "admin"
#define ATL_VERS    "3.10.2"

#endif
