
BUILD_DEPS = python39-dev pkgconfig
PYDEPS = distro pkgconfig "robotpy-opencv>=4.5.1" "robotpy-opencv-core-dev>=4.5.1"

PYPI_PACKAGE_NAME = robotpy-cscore
PYPI_PACKAGE_VERSION = 2021.0.2

include ../Mk/remote_whl.mk
