include ../Mk/ipkg.pre.mk

DEPS =

BUILD_CMD = /bin/false

INSTALL_CMD = /bin/false

GETDATA_TARARGS = --exclude=\*.py[co] \
		  --exclude=__pycache__ \
		  usr/local/lib/python3.4/test

EXTRA_CONTROL = postinst prerm

include ../Mk/ipkg.post.mk
