#!/bin/sh
# compile library files
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.5 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi /usr/local/lib/python3.5/compileall.py \
    -d lib/python3.5/test -f \
    -x badsyntax /usr/local/lib/python3.5/test
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.5 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi -O /usr/local/lib/python3.5/compileall.py \
    -d lib/python3.5/test -f \
    -x badsyntax /usr/local/lib/python3.5/test
