
.PHONY: all clean 	

clean:
	$(MAKE) -C python3 clean
	$(MAKE) -C python3-dev clean
	$(MAKE) -C python3-dbg clean

all:
	$(MAKE) -C python3 all
	$(MAKE) -C python3-dev all
	$(MAKE) -C python3-dbg all

