#!/bin/sh
if [ x"$D" = "x" ]; then
	if [ -x /sbin/ldconfig ]; then /sbin/ldconfig ; fi
fi
# compile library files
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.9 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi /usr/local/lib/python3.9/compileall.py \
    -d lib/python3.9 -f -q \
    -x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
    /usr/local/lib/python3.9
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.9 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi -O /usr/local/lib/python3.9/compileall.py \
    -d lib/python3.9 -f -q \
    -x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
    /usr/local/lib/python3.9
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.9 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi /usr/local/lib/python3.9/compileall.py \
    -d lib/python3.9/site-packages -f -q \
    -x badsyntax /usr/local/lib/python3.9/site-packages
/usr/bin/env PYTHONPATH=/usr/local/lib/python3.9 LD_LIBRARY_PATH=/usr/local/lib \
    /usr/local/bin/python3 -Wi -O /usr/local/lib/python3.9/compileall.py \
    -d lib/python3.9/site-packages -f -q \
    -x badsyntax /usr/local/lib/python3.9/site-packages
